filename1=str(input("Enter name of file 1   "))
filename2=str(input("Enter name of file 2   "))
file1=open(filename1,"r")
file2=open(filename2,"r")
placeholder1=file1.read()
placeholder2=file2.read()
file1.close()
file2.close()
file1=open(filename1,"w")
file2=open(filename2,"w")
file1.write(placeholder2)
file2.write(placeholder1)
file1.close()
file2.close()
file1=open(filename1,"r")
file2=open(filename2,"r")
print("file1: " + str(file1.read()))
print("file2: " + str(file2.read()))
